### ISSUE TITLE
App Crashes When Delete Project Without Selecting It

### ISSUE THREAD

**Issue by jasonfigueroa** [Trantuvan/odin-to-do-list#2]
**Steps to Recreate**
1. Create Project but to not click (select) it
2. Attempt to immediately delete the project
3. App crashes in projectController.js, line 54 due to the project variable being undefined.

![project-undefined-delete-crash](https://user-images.githubusercontent.com/9877492/191501152-1aa159eb-5e55-4544-8440-69c0a94b31ff.png)

Maybe implement something similar to the try/catch in the addTodo function in the same file.

![add-todo-try-catch](https://user-images.githubusercontent.com/9877492/191501513-c35ad769-ec5b-44ce-8166-c3bea3e7a401.PNG)

**Comment by Trantuvan** [comment]
I intentionally picking one project out to work on, so if I not picking one it will create bug.
I solve this with try and catch
