### ISSUE TITLE
App Crashes On Initial Load

### ISSUE THREAD

**Issue by jasonfigueroa** [Trantuvan/odin-to-do-list#3]
**Steps to Recreate**
1. Clear the local storage for the app

![clear-local-storage](https://user-images.githubusercontent.com/9877492/191502909-8b85bae5-84b6-49e3-ba39-2799919df1f3.png)

2. Refresh the page
3. The following is the error displayed in the console

![error-after-clearing-local-storage](https://user-images.githubusercontent.com/9877492/191502973-c4d93f85-c2db-40d5-9c29-092f390598a5.PNG)

**Comment by Trantuvan** [comment]
this is because I checking the length of projectArray before parse to js.
